server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Admincrud?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
